let weathercode = new Map();

weathercode.set(0, '../assets/day.svg');
weathercode.set(1, '../assets/cloudy-day-1.svg');
weathercode.set(2, '../assets/cloudy-day-3.svg');
weathercode.set('0N', '../assets/night.svg');
weathercode.set('1N', '../assets/cloudy-night-1.svg');
weathercode.set('2N', '../assets/cloudy-night-3.svg');
weathercode.set('3N', '../assets/cloudy.svg');
weathercode.set(3, '../assets/cloudy.svg');
weathercode.set(45, '../assets/cloudy.svg');
weathercode.set(61, '../assets/rainy-4.svg');
weathercode.set(63, '../assets/rainy-5.svg');
weathercode.set(65, '../assets/rainy-6.svg');
weathercode.set(80, '../assets/rainy-4.svg');
weathercode.set(81, '../assets/rainy-5.svg');
weathercode.set(82, '../assets/rainy-6.svg');
weathercode.set(85, '../assets/snowy-4.svg');
weathercode.set(71, '../assets/snowy-4.svg');
weathercode.set(72, '../assets/snowy-5.svg');
weathercode.set(73, '../assets/snowy-6.svg');
weathercode.set(86, '../assets/snowy-6.svg');
weathercode.set(95, '../assets/thunder.svg');
weathercode.set(96, '../assets/thunder.svg');
export default weathercode;